config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

#  get '/help', to: 'static_pages#help'

#  get '/about', to: 'static_pages#about'
  
#  get '/contact', to: 'static_pages#contact'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  
#  get '/signup', to: 'users#new'

  resources :labs

  get '/under_construction', to: 'static_pages#under_construction'
  
  # Under construction pages
  get '/help', to: 'static_pages#under_construction'
  get '/about', to: 'static_pages#under_construction'
  get '/contact', to: 'static_pages#under_construction'
  get '/signup', to: 'static_pages#under_construction'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/lab.rb
class Lab < ApplicationRecord
  validates :lab_name, presence: true
  validates :lab_website, presence: true
  validates :organization, presence: true
  validates :organization_website, presence: true
  validates :participant_location, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:message]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  private
    def contact_params
       params.require(:contact).permit(:name, :email, :message)
    end
  
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_lab, only: [:show, :edit, :update, :destroy]

  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
  end

  # GET /labs/new
  def new
    @lab = Lab.new
  end

  # GET /labs/1/edit
  def edit
  end

  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(lab_params)

    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render :show, status: :created, location: @lab }
      else
        format.html { render :new }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labs/1
  # PATCH/PUT /labs/1.json
  def update
    respond_to do |format|
      if @lab.update(lab_params)
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @lab }
      else
        format.html { render :edit }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @lab.destroy
    respond_to do |format|
      format.html { redirect_to labs_url, notice: 'Lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab
      @lab = Lab.find(params[:id])
    end

    # White list parameters.
    def lab_params
       params.require(:lab).permit(:lab_name, :lab_website, :organization, :organization_website, :participant_location, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def under_construction
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "StudyMe.Science"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<div id="contact-jumbotron" class="text-center jumbotron page-heading">
  <div class="container">
    <h1>Got a question?</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="text-center">Contact us!</h2>
      <div id="contact-well" class="well">
        <%= form_for @contact do |f| %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :message %>
            <%= f.text_area :message, rows: "7", class: 'form-control' %>
          </div>
          <%= f.submit 'Send', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/labs/_form.html.erb
<div id="contact-well" class="well">
  <%= form_for(lab) do |f| %>
    <% if lab.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(lab.errors.count, "error") %> prohibited this lab from being saved:</h2>
  
        <ul>
        <% lab.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :lab_name %>
                <%= f.text_field :lab_name, class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :lab_website %>
                <%= f.text_field :lab_website, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :organization %>
                <%= f.text_field :organization, class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :organization_website %>
                <%= f.text_field :organization_website, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :participant_location %>
                <%= f.text_field :participant_location, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :lab_description %>
            <%= f.text_area :description, rows: "7", class: 'form-control' %>
          </div>
          <%= f.submit 'Submit lab', class: 'btn btn-default' %>


  <% end %>
</div>

app/views/labs/edit.html.erb
<h1>Editing Lab</h1>

<%= render 'form', lab: @lab %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<p id="notice"><%= notice %></p>

<div id="labs-index-jumborton" class="text-center jumbotron page-heading">
  <div class="container">
    <h1>Explore science labs!</h1>
  </div>
</div>

<div id="labs-index-list" class="container">
  <% @labs.each do |lab| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="lab-card">
          <div class="featured-heading">
            <span class="lab-label"><a href="<%= lab.lab_website %>"><%= lab.lab_name %></span></a>
          </div>
          <div><span class="lab-label">Organization:</span> <a href="<%= lab.organization_website %>"><%= lab.organization %></a></div>
          <div><span class="lab-label">Participant location:</span> <%= lab.participant_location %></div>
          <div>
            <span class="lab-label">About the lab:</span>
            <%= lab.description %>
          </div>
          <div>
            <%= link_to "Learn more", lab.lab_website, class: "btn btn-lg btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/labs/new.html.erb
<div class="container offset-navbar">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="text-center">New Lab</h2>
      
      <%= render 'form', lab: @lab %>
      
      <%= link_to 'Back', labs_path %>

    </div>
  </div>
</div>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lab_path(@lab) %> |
<%= link_to 'Back', labs_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2017
    <%= link_to "StudyMe.Science", root_path %>
    | Web design & development by
    <a href="http://www.arigu.me">arigu.me</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, class: "nav-text-link" %></li>
      <li><%= link_to "Contact", new_contact_path, class: "nav-text-link" %></li>
      <li><%= link_to "Help", help_path, class: "btn btn-lg btn-default" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to root_path, id: "logo" do %>
      <%= image_tag("beaker-superperson-noBkgd.svg", alt: "StudyMe.Science logo") %>
    <% end %>
    <%= link_to root_path, id: "brand" do %>
      Study<span class="highlight">Me</span>.Science
    <% end  %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log in", under_construction_path, class: "btn btn-lg btn-primary" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type} text-center offset-navbar" %>
      <% end %>
    </div>
    <%= yield %>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StudyMe.Science App</h1>
<p>
  This is the About page.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StudyMe.Science App</h1>
<p>
  This is the help page.</p>

app/views/static_pages/home.html.erb
<div class="text-center jumbotron">
  <div class="container">
    <h1>Science is all about you</h1>
  
    <h2>
      Guide, support and engage science by participating in scientific studies.
      <br>
      And earn some <span class="highlight">$$</span> along the way!
    </h2>
  
    <%= link_to "Sign up for free", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Explore science labs", labs_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="featured-lab">
        <div class="featured-heading">
          <span class="lab-label">Featured lab:</span> <a href="http://www.hbs.edu/behave/">Computer Lab for Experimental Research</a>
        </div>
        <div><span class="lab-label">Organization:</span> <a href="http://www.hbs.edu">Harvard Business School</a></div>
        <div><span class="lab-label">Participant location:</span> Boston, MA</div>
        <div>
          <span class="lab-label">About the lab:</span>
          The Computer Lab for Experimental Research (CLER) studies human behavior 
          and decision-making by inviting participants from across the Boston area. 
          Participants are paid $15-25 per session to take part in lab-based studies 
          that contribute to this cutting-edge research.
        </div>
        <div>
          <%= link_to "Learn more", "http://www.hbs.edu/behave/Pages/participate.aspx", class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container" id="descriptive-section">
    <div class="row">
      <div class="col">
        <h1>Why participate?</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-md-4 text-center">
            <div><%= image_tag("lab-smiley-beakers.svg", alt: "StudyMe.Science logo", class: "lab-smiley") %></div>
            <div>
              <h2>Be a part of the scientific process!</h2>
              <p>Your participation in scientific studies makes them possible,
                and it guides science towards the right answers.</p>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div><%= image_tag("lab-smiley-dollars.svg", alt: "StudyMe.Science logo", class: "lab-smiley") %></div>
            <div>
              <h2>Earn a few extra bucks!</h2>
              <p>While it won't make you a millionaire, many studies pay for your participation.</p>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div><%= image_tag("lab-smiley-book.svg", alt: "StudyMe.Science logo", class: "lab-smiley") %></div>
            <div>
              <h2>Learn and engage with your scientific community!</h2>
              <p>See firsthand how scientific studies are conducted. 
                Witness cutting edge research. Get to know your local
                science labs. Most researchers welcome your questions about
                their research!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/static_pages/under_construction.html.erb
<% provide(:title, "Page under construction") %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="under-construction">
        <div><%= image_tag("lab-smiley-beakers.svg", alt: "StudyMe.Science logo", class: "lab-smiley") %></div>
        <h1>Hi there!</h1>
        <h2>This page is under construction at the moment, please check back later!</h2>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>